package yashbhandari.mafioso.Game;

public class Role {
    private String roleName;
    private String playerName;
    private boolean filled;
    private boolean alive;

    public Role(String roleName){
        this.roleName = roleName;
        this.playerName = "";
        this.filled = false;
        this.alive = true;
    }

    public void fillRole(String playerName){
        this.playerName = playerName;
        filled = true;
    }

    //  Autogenerated for serialization //

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public String getPlayerName() {
        return playerName;
    }

    public void setPlayerName(String playerName) {
        this.playerName = playerName;
    }

    public boolean isFilled() {
        return filled;
    }

    public void setFilled(boolean filled) {
        this.filled = filled;
    }

    public boolean isAlive() {
        return alive;
    }

    public void setAlive(boolean alive) {
        this.alive = alive;
    }
}
